In [1]:
print("Hello world")


Hello world


# Creating headers

# Heading 1
## Heading 2
### Heading 
#### Heading 4

# Making List
* Item 1
* Item 2
* Item 3



# Lab 2 



In [2]:
# 1.Convert the below list into numpy array then display the aaray
import numpy as np

my_list = [1, 2, 3, 4, 5]
numpy_array = np.array(my_list)

print("Numpy array:")
print(numpy_array)



Numpy array:
[1 2 3 4 5]


In [3]:
# 2.convert the below list into numpy aaray then display the array then display the first and last index and then multiply each element by 2 and display the result.
import numpy as np

# Convert the list into a numpy array
my_list = [1, 2, 3, 4, 5]
numpy_array = np.array(my_list)

# Display the numpy array
print("Numpy array:")
print(numpy_array)

# Display the first and last index elements
print("\nFirst element:", numpy_array[0])
print("Last element:", numpy_array[-1])

# Multiply each element by 2
result_array = numpy_array * 2

# Display the result
print("\nArray after multiplying each element by 2:")
print(result_array)



Numpy array:
[1 2 3 4 5]

First element: 1
Last element: 5

Array after multiplying each element by 2:
[ 2  4  6  8 10]
