<a href="https://colab.research.google.com/github/Supriyadandawate/DANLC_AF412025_Supriya/blob/main/Numpy_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives

In [5]:
import numpy as np

# Create arrays of 10 zeros, 10 ones, and 10 fives
zeros_array = np.zeros(10, dtype=int)
ones_array = np.ones(10, dtype=int)
fives_array = np.full(10, 5, dtype=int)

# Print each array separately in the required format
print("Array of 10 zeros:", zeros_array)
print("Array of 10 ones:", ones_array)
print("Array of 10 fives:", fives_array)


Array of 10 zeros: [0 0 0 0 0 0 0 0 0 0]
Array of 10 ones: [1 1 1 1 1 1 1 1 1 1]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]


#2. Create a 3x3 matrix with values ranging from 2 to 10

In [6]:
matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 matrix with values from 2 to 10:")
print(matrix)


3x3 matrix with values from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#3. Create an array with values ranging from 12 to 38

In [7]:
array = np.arange(12, 39)
print("Array with values from 12 to 38:")
print(array)


Array with values from 12 to 38:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


#4. Convert a list and a tuple into arrays

In [8]:
# Given list and tuple
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
my_tuple = ([8, 4, 6], [1, 2, 3])

# Convert to arrays
array_from_list = np.array(my_list)
array_from_tuple = np.array(my_tuple)

print("Array from list:", array_from_list)
print("Array from tuple:", array_from_tuple)


Array from list: [1 2 3 4 5 6 7 8]
Array from tuple: [[8 4 6]
 [1 2 3]]
